
Public Class DefineFreeboardRequirements
    Inherits WizardStep

    Friend WithEvents FreeboardPanel1 As Panel
    Friend WithEvents FreeboardPanel2 As Panel
    Friend WithEvents TextBox1 As TextBox
    Friend WithEvents TextBox2 As TextBox

    Private Sub InitializeComponent()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(DefineFreeboardRequirements))
        Me.FreeboardPanel1 = New System.Windows.Forms.Panel()
        Me.TextBox1 = New System.Windows.Forms.TextBox()
        Me.FreeboardPanel2 = New System.Windows.Forms.Panel()
        Me.TextBox2 = New System.Windows.Forms.TextBox()
        Me.StepPanel1.SuspendLayout()
        Me.StepPanel2.SuspendLayout()
        Me.FreeboardPanel1.SuspendLayout()
        Me.FreeboardPanel2.SuspendLayout()
        Me.SuspendLayout()
        '
        'StepPanel1
        '
        Me.StepPanel1.Controls.Add(Me.FreeboardPanel1)
        '
        'StepPanel2
        '
        Me.StepPanel2.Controls.Add(Me.FreeboardPanel2)
        '
        'FreeboardPanel1
        '
        Me.FreeboardPanel1.Controls.Add(Me.TextBox1)
        resources.ApplyResources(Me.FreeboardPanel1, "FreeboardPanel1")
        Me.FreeboardPanel1.Name = "FreeboardPanel1"
        '
        'TextBox1
        '
        resources.ApplyResources(Me.TextBox1, "TextBox1")
        Me.TextBox1.Name = "TextBox1"
        '
        'FreeboardPanel2
        '
        Me.FreeboardPanel2.Controls.Add(Me.TextBox2)
        resources.ApplyResources(Me.FreeboardPanel2, "FreeboardPanel2")
        Me.FreeboardPanel2.Name = "FreeboardPanel2"
        '
        'TextBox2
        '
        resources.ApplyResources(Me.TextBox2, "TextBox2")
        Me.TextBox2.Name = "TextBox2"
        '
        'DefineFreeboardRequirements
        '
        resources.ApplyResources(Me, "$this")
        Me.Name = "DefineFreeboardRequirements"
        Me.StepPanel1.ResumeLayout(False)
        Me.StepPanel2.ResumeLayout(False)
        Me.FreeboardPanel1.ResumeLayout(False)
        Me.FreeboardPanel1.PerformLayout()
        Me.FreeboardPanel2.ResumeLayout(False)
        Me.FreeboardPanel2.PerformLayout()
        Me.ResumeLayout(False)

    End Sub
    '
    ' The code above is generated by the Visual Studio Designer; do not edit it
    '
    ' The code below is added by the programmer.
    '
    Public Sub New(ByVal WinFlume As WinFlumeForm, ByVal Flume As Flume.FlumeType)
        ' This call is required by the designer.
        InitializeComponent()
        ' Add any initialization after the InitializeComponent() call.
        mWinFlume = WinFlume
        mFlume = Flume
    End Sub

    Public Overrides Function Panel1() As Panel
        Return Me.FreeboardPanel1
    End Function

    Public Overrides Function Panel2() As Panel
        Return Me.FreeboardPanel2
    End Function

    Public Overrides Function StartStep() As Boolean
        mWinFlume.WinFlumeTabControl.SelectTab(mWinFlume.DefineCanalTab)
        Dim defineCanal As DefineCanalControl = mWinFlume.GetDefineCanalControl
        defineCanal.DefineCanalTabControl.SelectTab(defineCanal.FreeboardRequirementTab)
        Return MyBase.StartStep()
    End Function

End Class
