
Public Class DefineControlSection
    Inherits WizardStep

    Friend WithEvents ControlSectionPanel1 As Panel
    Friend WithEvents ControlSectionPanel2 As Panel
    Friend WithEvents TextBox1 As TextBox
    Friend WithEvents TextBox2 As TextBox

    Private Sub InitializeComponent()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(DefineControlSection))
        Me.ControlSectionPanel1 = New System.Windows.Forms.Panel()
        Me.TextBox1 = New System.Windows.Forms.TextBox()
        Me.ControlSectionPanel2 = New System.Windows.Forms.Panel()
        Me.TextBox2 = New System.Windows.Forms.TextBox()
        Me.StepPanel1.SuspendLayout()
        Me.StepPanel2.SuspendLayout()
        Me.ControlSectionPanel1.SuspendLayout()
        Me.ControlSectionPanel2.SuspendLayout()
        Me.SuspendLayout()
        '
        'StepPanel1
        '
        Me.StepPanel1.Controls.Add(Me.ControlSectionPanel1)
        '
        'StepPanel2
        '
        Me.StepPanel2.Controls.Add(Me.ControlSectionPanel2)
        '
        'ControlSectionPanel1
        '
        Me.ControlSectionPanel1.Controls.Add(Me.TextBox1)
        resources.ApplyResources(Me.ControlSectionPanel1, "ControlSectionPanel1")
        Me.ControlSectionPanel1.Name = "ControlSectionPanel1"
        '
        'TextBox1
        '
        resources.ApplyResources(Me.TextBox1, "TextBox1")
        Me.TextBox1.Name = "TextBox1"
        '
        'ControlSectionPanel2
        '
        Me.ControlSectionPanel2.Controls.Add(Me.TextBox2)
        resources.ApplyResources(Me.ControlSectionPanel2, "ControlSectionPanel2")
        Me.ControlSectionPanel2.Name = "ControlSectionPanel2"
        '
        'TextBox2
        '
        resources.ApplyResources(Me.TextBox2, "TextBox2")
        Me.TextBox2.Name = "TextBox2"
        '
        'DefineControlSection
        '
        resources.ApplyResources(Me, "$this")
        Me.Name = "DefineControlSection"
        Me.StepPanel1.ResumeLayout(False)
        Me.StepPanel2.ResumeLayout(False)
        Me.ControlSectionPanel1.ResumeLayout(False)
        Me.ControlSectionPanel1.PerformLayout()
        Me.ControlSectionPanel2.ResumeLayout(False)
        Me.ControlSectionPanel2.PerformLayout()
        Me.ResumeLayout(False)

    End Sub
    '
    ' The code above is generated by the Visual Studio Designer; do not edit it
    '
    ' The code below is added by the programmer.
    '
    Public Sub New(ByVal WinFlume As WinFlumeForm, ByVal Flume As Flume.FlumeType)
        ' This call is required by the designer.
        InitializeComponent()
        ' Add any initialization after the InitializeComponent() call.
        mWinFlume = WinFlume
        mFlume = Flume
    End Sub

    Public Overrides Function Panel1() As Panel
        Return Me.ControlSectionPanel1
    End Function

    Public Overrides Function Panel2() As Panel
        Return Me.ControlSectionPanel2
    End Function

    Public Overrides Function StartStep() As Boolean
        mWinFlume.WinFlumeTabControl.SelectTab(mWinFlume.DefineControlTab)
        Dim defineControl As DefineControlControl = mWinFlume.GetDefineControlControl
        defineControl.DefineControlTabControl.SelectTab(defineControl.ControlSectionTab)
        Return MyBase.StartStep()
    End Function

End Class
