
Public Class DefineHeadMeasDevice
    Inherits WizardStep

    Friend WithEvents HeadMeasPanel1 As Panel
    Friend WithEvents HeadMeasPanel2 As Panel
    Friend WithEvents TextBox1 As TextBox
    Friend WithEvents TextBox2 As TextBox

    Private Sub InitializeComponent()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(DefineHeadMeasDevice))
        Me.HeadMeasPanel1 = New System.Windows.Forms.Panel()
        Me.TextBox1 = New System.Windows.Forms.TextBox()
        Me.HeadMeasPanel2 = New System.Windows.Forms.Panel()
        Me.TextBox2 = New System.Windows.Forms.TextBox()
        Me.StepPanel1.SuspendLayout()
        Me.StepPanel2.SuspendLayout()
        Me.HeadMeasPanel1.SuspendLayout()
        Me.HeadMeasPanel2.SuspendLayout()
        Me.SuspendLayout()
        '
        'StepPanel1
        '
        Me.StepPanel1.Controls.Add(Me.HeadMeasPanel1)
        '
        'StepPanel2
        '
        Me.StepPanel2.Controls.Add(Me.HeadMeasPanel2)
        '
        'HeadMeasPanel1
        '
        Me.HeadMeasPanel1.Controls.Add(Me.TextBox1)
        resources.ApplyResources(Me.HeadMeasPanel1, "HeadMeasPanel1")
        Me.HeadMeasPanel1.Name = "HeadMeasPanel1"
        '
        'TextBox1
        '
        resources.ApplyResources(Me.TextBox1, "TextBox1")
        Me.TextBox1.Name = "TextBox1"
        '
        'HeadMeasPanel2
        '
        Me.HeadMeasPanel2.Controls.Add(Me.TextBox2)
        resources.ApplyResources(Me.HeadMeasPanel2, "HeadMeasPanel2")
        Me.HeadMeasPanel2.Name = "HeadMeasPanel2"
        '
        'TextBox2
        '
        resources.ApplyResources(Me.TextBox2, "TextBox2")
        Me.TextBox2.Name = "TextBox2"
        '
        'DefineHeadMeasDevice
        '
        resources.ApplyResources(Me, "$this")
        Me.Name = "DefineHeadMeasDevice"
        Me.StepPanel1.ResumeLayout(False)
        Me.StepPanel2.ResumeLayout(False)
        Me.HeadMeasPanel1.ResumeLayout(False)
        Me.HeadMeasPanel1.PerformLayout()
        Me.HeadMeasPanel2.ResumeLayout(False)
        Me.HeadMeasPanel2.PerformLayout()
        Me.ResumeLayout(False)

    End Sub
    '
    ' The code above is generated by the Visual Studio Designer; do not edit it
    '
    ' The code below is added by the programmer.
    '
    Public Sub New(ByVal WinFlume As WinFlumeForm, ByVal Flume As Flume.FlumeType)
        ' This call is required by the designer.
        InitializeComponent()
        ' Add any initialization after the InitializeComponent() call.
        mWinFlume = WinFlume
        mFlume = Flume
    End Sub

    Public Overrides Function Panel1() As Panel
        Return Me.HeadMeasPanel1
    End Function

    Public Overrides Function Panel2() As Panel
        Return Me.HeadMeasPanel2
    End Function

    Public Overrides Function StartStep() As Boolean
        mWinFlume.WinFlumeTabControl.SelectTab(mWinFlume.DefineControlTab)
        Dim defineControl As DefineControlControl = mWinFlume.GetDefineControlControl
        defineControl.DefineControlTabControl.SelectTab(defineControl.HeadMeasurementTab)
        Return MyBase.StartStep()
    End Function

End Class
