
Public Class ProjectDescription
    '
    ' The code above is generated by the Visual Studio Designer; do not edit it
    '
    ' The code below is added by the programmer to implement the Wizard Step
    '
    Public Sub New(ByVal WinFlume As WinFlumeForm, ByVal Flume As Flume.FlumeType)
        ' This call is required by the designer.
        InitializeComponent()
        ' Add any initialization after the InitializeComponent() call.
        mWinFlume = WinFlume
        mFlume = Flume
    End Sub

    Public Overrides Function Panel1() As Panel
        Return Me.ProjectDescriptionPanel1
    End Function

    Public Overrides Function Panel2() As Panel
        Return Me.ProjectDescriptionPanel2
    End Function

    Public Overrides Function NextButton() As Boolean
        '
        ' Update the Flume's description
        '
        Dim description As String = mFlume.Description.Trim
        Dim dbDescription As New db_GetStringValue(description) With {
            .Title = My.Resources.EnterFlumeDescription,
            .Instructions = My.Resources.Description & ":"}
        Dim result As DialogResult = dbDescription.ShowDialog
        If (result = DialogResult.OK) Then
            description = dbDescription.Value
            mFlume.Description = description
            mWinFlume.UpdateUI()
        End If

        Return MyBase.NextButton()
    End Function

End Class
