
Imports WinFlume.UnitsDialog

Public Class SystemOfUnits
    '
    ' The code above is generated by the Visual Studio Designer; do not edit it
    '
    ' The code below is added by the programmer to implement the Wizard Step
    '
    Public Sub New(ByVal WinFlume As WinFlumeForm, ByVal Flume As Flume.FlumeType)
        ' This call is required by the designer.
        InitializeComponent()
        ' Add any initialization after the InitializeComponent() call.
        mWinFlume = WinFlume
        mFlume = Flume
    End Sub

    Public Overrides Function Panel1() As Panel
        Return Me.SystemOfUnitsPanel1
    End Function

    Public Overrides Function Panel2() As Panel
        Return Me.SystemOfUnitsPanel2
    End Function

    Public Overrides Function NextButton() As Boolean
        ' Let user select the units system
        Dim results As DialogResult = mWinFlume.ShowUnitsDialog(UnitsDialogModes.SetNewProjectUnits)
        Return MyBase.NextButton()
    End Function

End Class
